export const ADMIN_ROUTE='/admin'
export const ADMINLOGIN_ROUTE='/admin/login'
export const LOGIN_ROUTE='/login'
export const REGISTRATION_ROUTE='/registration'

export const HOME_ROUTE='/'
export const ROOMS_ROUTE='/rooms/:id'
export const SEARCH_ROUTE='/search/:id'
export const PROFILE_ROUTE='/profile'
export const ORDERS_ROUTE='/orders'